version: '3.1'
services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/bitnami/mysql/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    #ports:
    #  - "3306:3306"
volumes:
  mysql_data:
    driver: local